update test action

diff --git a/.github/workflows/auto_test.yml b/.github/workflows/auto_test.yml
--- a/.github/workflows/auto_test.yml
+++ b/.github/workflows/auto_test.yml
@@ -43,27 +43,27 @@ jobs:
         continue-on-error: true
 
       # テスト結果の表示
-      - name: Upload Unit Test Results
-        if: ${{ always() }}
-        uses: actions/upload-artifact@v2
-        with:
-          name: Unit Test Results (Python ${{ matrix.python-version }})
-          path: results/*.xml
+      # - name: Upload Unit Test Results
+      #   if: ${{ always() }}
+      #   uses: actions/upload-artifact@v2
+      #   with:
+      #     name: Unit Test Results (Python ${{ matrix.python-version }})
+      #     path: results/*.xml
 
-      - name: Download Artifacts
-        if: success() || failure()
-        uses: actions/download-artifact@v2
-        with:
-          path: artifacts
+      # - name: Download Artifacts
+      #   if: success() || failure()
+      #   uses: actions/download-artifact@v2
+      #   with:
+      #     path: artifacts
 
-      - name: Publish Unit Test Results
-        uses: EnricoMi/publish-unit-test-result-action@v2
-        with:
-          junit_files: artifacts/**/*.xml
+      # - name: Publish Unit Test Results
+      #   uses: EnricoMi/publish-unit-test-result-action@v2
+      #   with:
+      #     junit_files: artifacts/**/*.xml
 
       - name: Print time
         run: |
-          echo "This is ${{ matrix.python-version }} summary!" >> $GITHUB_STEP_SUMMARY
+          echo "This is Python ${{ matrix.python-version }} summary!" >> $GITHUB_STEP_SUMMARY
       
       - name: Pytest coverage comment
         # if: ${{ steps.is_main.outputs.flag == '1' }}
@@ -78,4 +78,5 @@ jobs:
         id: check_status
         run: |
           echo -e ${{ steps.coverageComment.outputs.summaryReport }} >> $GITHUB_STEP_SUMMARY
+          cat ./results/pytest-coverage.txt >> $GITHUB_STEP_SUMMARY
     
